matrix:
  include:
    - os: osx
      osx_image: xcode12
      env: SWIFT_VERSION=5.2
language: generic
sudo: required
dist: trusty
script:
  - swift package generate-xcodeproj
  - xcodebuild test -scheme CodableWrappers -destination platform="macOS" -enableCodeCoverage YES -derivedDataPath .build/derivedData
after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^CodableWrappers$' -D .build/derivedData